name: Alpine Cron Image Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: registry.sonnvest.de
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build base Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: registry.sonnvest.de/sonnvest/alpine-cron:latest
          platforms: linux/amd64
          
      - name: Build Node.js 22 Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.node-22
          push: true
          tags: registry.sonnvest.de/sonnvest/alpine-cron:node-22
          platforms: linux/amd64
